name: Build and Push Docker Image to ACR

on:
  push:
    branches: [ main ]  # ou qualquer branch/evento que quiseres

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}

      - name: Build and push Docker image
        run: |
          IMAGE="${{ secrets.AZURE }}/myapp:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE
